### PR TITLE
Fixing bug where writeBuffer was throwing an error for mode w+

### PR DESCRIPTION
**Pull request by fresheneesz**

### CODE REVIEW

**Comment by imlucas** [comment]
Thanks, @fresheneesz!  On further review, we cannot accept this pull request. Concurrent append operations are unsafe as they can easily corrupt the files. Making this possible would require a re-design of the `gridfs` storage specification.

**Comment by fresheneesz** [comment]
@imlucas 

"Concurrent append operations are unsafe"

Of course, concurrent appends (or writes in general) are unsafe, but that's not what I'm doing. I'm simply trying to append to a file - nothing concurrent is happening. That line of code is causing things to fail. I'm confused why you're assuming that I'm doing multiple appends to the same file concurrently.

**Comment by christkv** [comment]
It does not matter if you are doing it in a single thread. it's an unsafe operation for the driver and a giant shotgun to shoot yourself in the foot and the reason we removed the feature. For every 1 person doing it right there was 10 people doing it wrong unfortunately.

There are some npm packages that pertain to work around this 

https://www.npmjs.com/package/gridfs-locking-stream

However I'm not sure if it works and the state of the project.

**Comment by fresheneesz** [comment]
@christkv So are you saying that the "w+" mode was removed entirely as a feature? Why isn't an error thrown if you pass in "w+" to the GridStore constructor then? And why do the docs [still say](https://github.com/mongodb/node-mongodb-native/blob/master/docs/gridfs.md) that "w+" is an accepted mode?

**Comment by christkv** [comment]
w+ is only supported for meta-data changes not the file content itself as the meta-data can be changed in one atomic operation.

**Comment by fresheneesz** [comment]
@christkv That makes 0 sense. The documentation says "'w+' (Append): Finds the last chunk, and keeps writing after it." It says nothing about meta data. You don't need to open up the file to write meta data anyway, as you can just modify the document in fs.files directly with a basic mongo update. So what are you talking about?

**Comment by fresheneesz** [comment]
And please explain to me how a single append operation is in any way unsafe as long as other appends aren't happening concurrently. If that were true, your basic OS filesystem w+ writes would also be unsafe.

**Comment by fresheneesz** [comment]
@christkv Can you please answer the following question that you previously ignored. I have to believe we're misunderstanding eachother:

"it's an unsafe operation"

What is the "it" you're talking about? What is an unsafe operation? Surely simply appending to a file isn't unsafe.

**Comment by christkv** [comment]
Append does not lock a file in gridfs. Multiple concurrent operations can try to append to the same file causing data to be overwritten. Unsafe means there is a very high likely hood of data corruption when using w+ in drivers that allowed it. It was removed due to users running into this exact issue in production systems. It's been out for several years already. Until the GridFS specification allows some sort of safe concurrent appending (either via locks or special support in mongodb) it will not be re-introduced as an option. GridStore is also a legacy API at this point as we implement the joint new API.

https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst

**Comment by fresheneesz** [comment]
@christkv 

"Append does not lock a file in gridfs."

This raises so many questions. Does overwrite (mode "w") lock a file in gridfs? It should, because otherwise you can get read corruption if a file is overridden in the middle of a set of reads. Isn't the whole point of opening a file to lock that file?

If mode "w" locks the file, why wouldn't the same be done for "w+"? 

"GridStore is also a legacy API at this point as we implement the joint new API."

Is the new API implemented? What's it called? Gridfs? Are GridStore and GridFS different? 

"it will not be re-introduced as an option"

Why doesn't `new mongodb.GridStore(db, _id, "+w")` throw an error if that option isn't valid?

**Comment by christkv** [comment]
1. w creates a new file with a unique objectId unless you override with your own custom id. No concurrency ever possible and thus no file locking through the API provided needed.
2. http://mongodb.github.io/node-mongodb-native/2.2/api/GridFSBucket.html and http://mongodb.github.io/node-mongodb-native/2.2/tutorials/gridfs/streaming/
3. w+ is valid but only for changing details about the document in the files collection not any of the actual binary chunks in the chunks collection.

There is no way to guarantee the integrity of a GridFS file append as the specification stands now. Any such guarantee would have to include options as mentioned above to make it feasible.

If you need append please have a look at the provided link above that addresses your specific concern.

https://www.npmjs.com/package/gridfs-locking-stream

**Comment by fresheneesz** [comment]
@christkv 

"w+ is valid but only for changing details about the document in the files collection not any of the actual binary chunks in the chunks collection."

The docs I were looking at give no mention of how to manipulate the metadata with a GridStore object. How would you do that? And why would you use "w+" to modify metadata if you could just use "w"? This still doesn't make any sense to me.

"No concurrency ever possible [with mode w]"

That's not true. If you create the file, and then open it again with mode w, it'll overwrite just fine. If no locking is happening, someone could be reading the file *as* you're overwriting it. There are obvious read-corruption problems there.

**Comment by fresheneesz** [comment]
@imlucas Could you add some clarity here? I'm just not understanding what christkv is saying.

**Comment by marcj** [comment]
Mongodb has generally the problem with multi-document updates as there are not such thing as transactions. Fortunately, in a few weeks we'll get Mongodb 4.0 which has [transactions](https://www.mongodb.com/transactions). So GridFS implementations will be able to have an `append` method + it's way more performant than using custom locks using for example with [gridfs-locks](https://github.com/vsivsi/gridfs-locks).

**Comment by marcj** [comment]
@fresheneesz Having an append mode means updating multiple collection at the same time (add fs.chunks row + update fs.files to set the correct `length`), which is simply not possible in Mongodb atomatically -> which means it will result in errors sooner or later. So it's a good decision to not even implement it.

**Comment by fresheneesz** [comment]
@marcj I see what you're saying, but if you add chunk rows and never get to set the correct length, you'll take up some additional space but this file will still look just like nothing happened, right? (Since the length wasn't changed, it'd pretend those new chunk rows just don't exist).

**Pull request closed without merging**
