### PR TITLE
refactor: deprecate remove, removeOne, insertMany bulk operations

### PR DESCRIPTION
**Pull request by emadum**
NODE-2978

### CODE REVIEW

**Review by durran — APPROVED** [review]
LGTM

**Review by dariakp — APPROVED** [review]
👍🏻

**Comment by ImRodry** [comment]
Sorry to say this after this has already been merged but what's gonna happen to this line if insertMany is deprecated? https://github.com/mongodb/node-mongodb-native/blob/3.6/lib/collection.js#L1024

**Comment by emadum** [comment]
> Sorry to say this after this has already been merged but what's gonna happen to this line if insertMany is deprecated? https://github.com/mongodb/node-mongodb-native/blob/3.6/lib/collection.js#L1024

No worries! This PR only deprecates the `insertMany` bulk operation, created via e.g. `collection.initializedOrderBulkOp().insertMany(...)`. The `collection.insertMany` helper is still available.

**Comment by ImRodry** [comment]
Ah okay, sorry for the confusion!

**Pull request merged**
