### PR TITLE
typo in url_parser.js resulting in "replSetServerOptions is not defined" when connecting over ssl

### PR DESCRIPTION
**Pull request by japel**
see https://jira.mongodb.org/browse/NODE-661

### CODE REVIEW

**Comment by christkv** [comment]
merged manually

**Comment by fgouteroux** [comment]
+1

**Comment by japel** [comment]
Any info in which release this will be adopted? Currently it is impossible to connect over ssl with self-signed certificates

**Comment by christkv** [comment]
We are tracking a support ticket internally that we need to resolve before a new release goes out. This means it could take a week or two more.

**Comment by japel** [comment]
@christkv thanks for the info!

**Pull request closed without merging**
