### PR TITLE
WIP: build automation

### PR DESCRIPTION
**Pull request by daprahamian**
WIP for a plan for build automation. ~~This is the first stage, which makes the versioning process easier. We can now just run `npm version [major|minor|patch]` and have the changelog updated.~~ This now uses [standard-version](https://www.npmjs.com/search?q=standard-version)

The remaining items to figure out:

+ [ ] Ensure that build tests pass before submitting: This could be accomplished by `"prerelease": "npm test". However, our tests are not stable enough to make it easy to release.
+ [ ] Automatically push after cutting a release: This could be done by `"postrelease": "git push && git push --tags"`, but we push releases on multiple lines, so it can get complicated.
+ [ ] Automatically publish to npm
+ [ ] Auto-upgrade to the proper version of `mongodb-core`

I'd love feedback / discussion on these points @mbroadst @kvwalker

### CODE REVIEW

**Comment by mbroadst** [comment]
I was thinking maybe we'd use something like [standard-version](https://github.com/conventional-changelog/standard-version#readme), or maybe fully jumping to [semantic-release](https://github.com/semantic-release/semantic-release) - what are your thoughts on those tools?

**Comment by daprahamian** [comment]
@mbroadst The reason I didn't pursue those is b/c of the way it enforces minor bumps for features. I figured we'd want more control over what tag we wanted.

If we're okay with going that route, I think semantic-release or standard-release would work fine.

**Comment by mbroadst** [comment]
@daprahamian IMO we've just been a bit sloppy with minor releases wrt semver in the past, I'd like to get on board with this. Let's evaluate whether `semantic-release` is _too_ automated for us, but otherwise I'd like to go with one of those solutions.

**Comment by daprahamian** [comment]
This seems to be superseded by https://github.com/mongodb/node-mongodb-native/commit/875b925ab13694a6665bc9686ddf12d9855bc369, so I'll close this for now

**Pull request closed without merging**
