### PR TITLE
docs(mongo-client): the new method MongoClient().connect() was wrongly…

### PR DESCRIPTION
**Pull request by krufab**
… marked as deprecated instead of the old static MongoClient.connect()

### CODE REVIEW

**Comment by krufab** [comment]
Hello @jlord,
would it be possible to review this PR? Or how's the procedure?
Thanks

**Comment by krufab** [comment]
Ok, I've updated the code

**Comment by jlord** [comment]
Thanks so much @krufab! ✨

**Comment by Jeff-Lewis** [comment]
This one threw me off. Can we update latest publsihed [API docs](http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html)?

**Comment by Leibosite** [comment]
also wrong in version 3.0.7,please check!

**Pull request merged**
