### PR TITLE
fix(mongo_client_ops): only skip authentication if no authMechanism is specified

### PR DESCRIPTION
**Pull request by kvwalker**
Fixes NODE-1840

### CODE REVIEW

**Comment by mbroadst** [comment]
Agreed, @kvwalker can you test this with next as well?

**Comment by kvwalker** [comment]
This bug does still exist on `next` so I'll work on a patch for that.

**Comment by mbroadst** [comment]
re-approve 👍

**Comment by HunderlineK** [comment]
We have been experiencing this issue ("command aggregate requires authentication") with node-mongodb-native drive >3.4.1 (so minimum 3.4.1) and Mongo 4.2. It's intermittent and eventually goes away by itself or sometimes requires us to restart the server. This is the full trace:

```

"MongoError: command aggregate requires authentication\n    at Connection.eval (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:27164:61)\n    at Connection.emit (events.js:198:13)\n    at processMessage (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:26005:10)\n    at TLSSocket.eval (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:26174:15)\n    at TLSSocket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at TLSSocket.Readable.push (_stream_readable.js:224:10)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"
```

**Comment by mbroadst** [comment]
Hi @HunderlineK can you please open a [JIRA ticket](https://jira.mongodb.org/projects/NODE/issues) for this? Thanks!

**Comment by HunderlineK** [comment]
@mbroadst Thanks for the link, done! 
https://jira.mongodb.org/browse/NODE-2513

(sorry for the formatting of the issue, couldn't edit it afterwards!)

**Pull request merged**
