### PR TITLE
test(NODE-5183): Clean up Azure resources on task failure

### PR DESCRIPTION
**Pull request by kevinAlbs**
#### What is changing?

- Reload expansions before deleting Azure resources

Verified with this patch: https://spruce.mongodb.com/version/64345805850e61555185df30

##### Is there new documentation needed for these changes?

No.

#### What is the motivation for this change?

This is an improvement to the `testazurekms_task_group` added as part of DRIVERS-2411. https://github.com/mongodb/mongo-c-driver/pull/1234 explains this improvement.

### Double check the following

- [x] Ran `npm run check:lint` script
- [x] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [x] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- ~~[ ] Changes are covered by tests~~ N/A. Only modifies Evergreen config.
- ~~[ ] New TODOs have a related JIRA ticket~~ N/A. No new TODOs were added.

### CODE REVIEW

**Review by dariakp — CHANGES_REQUESTED** [review]
@kevinAlbs Thank you for adding the change! Because of the way we set up the config, this change actually needs to be in the `config.in.yml` (which gets turned into config.yml via the generate_evergreen_tasks.js). 

Side note: our lint task is a bit of a catch all - it does a lot of this sort of validation along with the actual code linting:

```
[2023/04/10 19:12:11.269] Detected .evergreen/config.yml not up to date
[2023/04/10 19:12:11.269] Make sure to run: node .evergreen/generate_evergreen_tasks.js
```
If you don't want to set up `node` (assuming you don't already have it in your dev env), we can make this fix ourselves.

**Comment by kevinAlbs** [comment]
> Because of the way we set up the config, this change actually needs to be in the `config.in.yml` (which gets turned into config.yml via the generate_evergreen_tasks.js).

Thank you for the help. edecf550b2a04506e044ce633f1cb91f04662b43 updates to use `config.in.yml`.

**Review by dariakp — APPROVED** [review]

**Comment by dariakp** [comment]
@kevinAlbs should https://jira.mongodb.org/browse/DRIVERS-2600 go into Teams Implementing or are we expecting more changes in addition to this one?

**Review by baileympearson — APPROVED** [review]

**Comment by kevinAlbs** [comment]
> @kevinAlbs should https://jira.mongodb.org/browse/DRIVERS-2600 go into Teams Implementing or are we expecting more changes in addition to this one?

DRIVERS-2600 has been moved to Teams Implementing.

**Pull request merged**
