### PR TITLE
APM for 'serialize command' step

### PR DESCRIPTION
**Pull request by dschenkelman**
Opening up this PR for discussion, not meant to be the final version.

# What?
This changes creates three new APM events, related to the `serializeCommand` operation.

# Why?
The `CommandXEvent`s are very good for high level visibility but lack details. As an engineer that has developed with node.js + MongoDB for a while, I've usually found myself wanting to separate:

1. MongoDB server/DB side command execution time
1. MongoDB client side command execution time delays, especially related to serialization

Item #2 can be particularly useful to identify either updates/inserts of large document sets (which are bad because serialization time blocks the event loop) and large result sets from queries (not in this PR).

This is what the events look like when logged to the console:
```
succeeded CommandSucceededEvent {
  duration: 1.702143,
  commandName: 'endSessions',
  reply: { ok: 1 },
  requestId: 4,
  connectionId: 'localhost:27017',
  metadata: 
   CommandMetadata {
     bsonSerialization: 
      BSONSerializationData {
        type: 'bsonSerialization',
        buffersLength: 141,
        duration: 0.091494 } } }
```

In this case as a developer I could consider the `duration` and `buffersLength` to be fairly high. This can then be either sent to metrics, logs and even tracing services with the appropriate context tracking.

Also, if this is useful I'd like to explore doing the same thing for "deserialization time", aiming to expose timing and size metrics about query results, e.g. knowing about `find` queries that returns > 1MB of size and block the event loop while deserializing such a big chunk of data.

### CODE REVIEW

**Comment by dschenkelman** [comment]
@mbroadst @daprahamian any feedback on this one?

**Comment by daprahamian** [comment]
Hey @dschenkelman,

Sorry this is taking so long. We're currently swamped with feature requirements, so it will be a few more weeks before we can circle back to this.

\-Dan

**Comment by dschenkelman** [comment]
> Hey @dschenkelman,
> 
> Sorry this is taking so long. We're currently swamped with feature requirements, so it will be a few more weeks before we can circle back to this.
> 
> -Dan

I understand. Any chance that in the meantime I can get a couple of pointers on how to add similar instrumentation but for query result serialization instead of commands?

I'd love to take a stab at that 😄

**Comment by dschenkelman** [comment]
@daprahamian hey 👋, happy new year! any news on this one? anything I can do to help get it merged?

**Comment by daprahamian** [comment]
@dschenkelman I am no longer a maintainer on the project, pinging @mbroadst.

**Comment by dschenkelman** [comment]
thanks @daprahamian. looking forward to hearing back from @mbroadst

**Comment by mbroadst** [comment]
Hey @dschenkelman, sorry the PR was autoclosed! I deleted that branch which is what I think forced the PR shut. If you can rebase against `3.5` or `3.6`, then we can see about modifying your code for the `4.0` release. We had a lull there where I was the only developer, but now have a sizeable team and can investigate bigger changes like this again!

**Pull request closed without merging**
