### PR TITLE
convert custom readPreference objects in collection.js

### PR DESCRIPTION
**Pull request by Machyne**
Add the same fix from db.js to collection.js :)

### CODE REVIEW

**Comment by christkv** [comment]
it cannot be a CoreReadPreference, it needs to be a ReadPreference object

**Comment by christkv** [comment]
you can run the tests by doing

node test/runner.js -t functional -l

and

node test/runner.js -t functional -e replicaset -l

**Comment by Machyne** [comment]
The two other cases were using CoreReadPreference, should I change those as well?

**Comment by christkv** [comment]
no this actually looks right after having a better look. I'll merge on monday if it passes the test replicaset suite.

**Pull request merged**
