### PR TITLE
Fixed strange error that started happening in 1.2.9 of mongodb-core

### PR DESCRIPTION
**Pull request by amit777**
I'm not sure how to reproduce it, but this adds an extra safety check to make sure isDead is defined.

### CODE REVIEW

**Comment by christkv** [comment]
do you know what operation was being executed at the time ? and what version of the mongodb driver you are using.

**Comment by christkv** [comment]
also what version of node.

**Comment by christkv** [comment]
this error suggests that isDead is not correctly inherited from the mongodb-core cursor class which is very strange.

**Comment by amit777** [comment]
iojs 2.5.0
mongoose 4.1.3 (latest) which contains:
- mongodb 2.0.40  -> mongo-core 1.2.9

It happens when my application is starting up. sporadically.   Will try to narrow down a little further an message back.  If you need access to my environment somehow, I'm sure we can make that work.

**Comment by amit777** [comment]
I did a simple console.log(self) right before the error occurs.  Below is the output. Not sure if it's helpful at all.  I just noticed one of the parameters is connectionTimeout: 10000 which seems to coincide with with how long it takes to crash at startup. I thought I tried changing this to 30000 before but maybe it's not taking affect. I'll try increasing the timeout again.

```
{ connection: null,
  server: null,
  disconnectHandler:
   { s: { storedOps: [], storeOptions: [Object], topology: [Object] },
     length: [Getter] },
  bson: {},
  ns: 'sgapp.$cmd',
  cmd: { listIndexes: 'users', cursor: {} },
  options:
   { cursorFactory: { [Function] super_: [Object], INIT: 0, OPEN: 1, CLOSED: 2 },
     promiseLibrary: [Function: Promise],
     disconnectHandler: { s: [Object], length: [Getter] } },
  topology:
   { domain: null,
     _events:
      { reconnect: [Function],
        timeout: [Object],
        error: [Object],
        close: [Object],
        joined: [Function],
        left: [Function],
        ping: [Function],
        ha: [Function],
        fullsetup: [Function],
        all: [Function] },
     _eventsCount: 10,
     _maxListeners: undefined,
     s:
      { options: [Object],
        logger: [Object],
        id: 5,
        index: 0,
        haId: 1,
        credentials: [],
        Cursor: [Object],
        bsonInstance: {},
        bson: {},
        secondaryOnlyConnectionAllowed: false,
        haInterval: 10000,
        debug: false,
        setName: undefined,
        emitError: true,
        tag: undefined,
        disconnectHandler: [Object],
        connectingServers: {},
        readPreferenceStrategies: [Object],
        authProviders: [Object],
        disconnectedServers: [],
        initialConnectionServers: [],
        highAvailabilityProcessRunning: true,
        fullsetup: true,
        all: false,
        seedlist: [Object],
        authInProgress: false,
        authInProgressServers: [],
        minHeartbeatFrequencyMS: 500,
        replState: [Object] },
     bson: [Getter],
     id: [Getter],
     haInterval: [Getter],
     state: [Getter],
     type: [Getter] },
  cursorState:
   { cursorId: null,
     cmd: { listIndexes: 'users', cursor: {} },
     documents: [],
     cursorIndex: 0,
     dead: false,
     killed: false,
     init: false,
     notified: false,
     limit: 0,
     skip: 0,
     batchSize: 1000,
     currentLimit: 0,
     transforms: undefined },
  callbacks: null,
  logger: { className: 'Cursor' },
  _readableState:
   { objectMode: true,
     highWaterMark: 16,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  s:
   { maxTimeMS: null,
     state: 0,
     streamOptions: {},
     bson: {},
     ns: 'sgapp.$cmd',
     cmd: { listIndexes: 'users', cursor: {} },
     options:
      { cursorFactory: [Object],
        promiseLibrary: [Function: Promise],
        disconnectHandler: [Object] },
     topology:
      { domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        s: [Object],
        bson: [Getter],
        id: [Getter],
        haInterval: [Getter],
        state: [Getter],
        type: [Getter] },
     topologyOptions:
      { socketOptions: {},
        size: 5,
        reconnect: true,
        emitError: true,
        cursorFactory: [Object],
        disconnectHandler: [Object],
        setName: undefined,
        bson: {},
        connectionTimeout: 10000,
        native_parser: true,
        read_preference: 'primary',
        forceServerObjectId: false,
        w: 1,
        promiseLibrary: [Function: Promise] },
     promiseLibrary: [Function: Promise] },
  timeout: false,
  sortValue: undefined,
  readPreference: undefined }
```

**Comment by christkv** [comment]
try to set a high socketTimeout as well

**Comment by amit777** [comment]
my dbOptions are as follows for when I connect to mongo (notice the 30000 ms. I'm not sure if this taking effect):
```
"dbOptions": {
      "db": {"native_parser": true},
      "replSet": {
        "rs_name": "mongocluster",
        "socketOptions": { "keepAlive": 1, "connectTimeoutMS": 30000 }
        }
    },
```

**Comment by christkv** [comment]
it should, try setting socket timeout as well to a higher value like 60s socketTimeoutMS

**Comment by christkv** [comment]
This test confirms if the properties are set correctly.

```js
exports['Should correctly pass through extra server options'] = {
  metadata: {
    requires: {
      node: ">0.8.0",
      topology: ['single']
    }
  },

  // The actual test we wish to run
  test: function(configuration, test) {
    var MongoClient = configuration.require.MongoClient;
    MongoClient.connect(configuration.url(), {
      server: {
          poolSize: 10
        , autoReconnect:false
        , socketOptions: {
            noDelay: false
          , keepAlive: 100
          , connectTimeoutMS: 444444
          , socketTimeoutMS: 555555
        }
      },
    }, function(err, db) {
      test.equal(10, db.s.topology.s.poolSize);
      test.equal(false, db.s.topology.autoReconnect);
      test.equal(444444, db.s.topology.s.clonedOptions.connectionTimeout);
      test.equal(555555, db.s.topology.s.clonedOptions.socketTimeout);
      test.equal(true, db.s.topology.s.clonedOptions.keepAlive);
      test.equal(100, db.s.topology.s.clonedOptions.keepAliveInitialDelay);

      db.close();
      test.done();
    });
  }
}
```

**Comment by christkv** [comment]
and for replicaset

```js
exports['Should correctly pass through extra replicaset options'] = {
  metadata: {
    requires: {
      node: ">0.8.0",
      topology: ['replicaset']
    }
  },

  // The actual test we wish to run
  test: function(configuration, test) {
    var MongoClient = configuration.require.MongoClient;
    var url = configuration.url().replace('rs_name=rs', 'rs_name=rs1')
    MongoClient.connect(url, {
      replSet: {
          ha:false
        , haInterval: 10000
        , replicaSet: 'rs'
        , secondaryAcceptableLatencyMS: 100
        , connectWithNoPrimary: true
        , poolSize: 1
        , socketOptions: {
            noDelay: false
          , keepAlive: 100
          , connectTimeoutMS: 444444
          , socketTimeoutMS: 555555
        }
      }
    }, function(err, db) {
      test.equal(false, db.s.topology.s.clonedOptions.ha);
      test.equal(10000, db.s.topology.s.clonedOptions.haInterval);
      test.equal('rs', db.s.topology.s.clonedOptions.replicaSet);
      test.equal(100, db.s.topology.s.clonedOptions.acceptableLatency);
      test.equal(true, db.s.topology.s.clonedOptions.secondaryOnlyConnectionAllowed);
      test.equal(1, db.s.topology.s.clonedOptions.poolSize);

      test.equal(444444, db.s.topology.s.clonedOptions.connectionTimeout);
      test.equal(555555, db.s.topology.s.clonedOptions.socketTimeout);
      test.equal(true, db.s.topology.s.clonedOptions.keepAlive);
      test.equal(100, db.s.topology.s.clonedOptions.keepAliveInitialDelay);

      db.close();
      test.done();
    });
  }
}

```

**Comment by amit777** [comment]
Alright.. I think i found the issue. this was my stupidity I think.  I have a large koajs app that has multiple apps mounted.  one of the apps was doing mongo connect a second time which I think was causing the race condition.  I'll continue to test my fix.

**Comment by amit777** [comment]
closing.. sorry to have bothered you with this.

**Comment by christkv** [comment]
actually it's great :+1: as it was not a difficult to track down issue in the driver which makes me happy :). I guess the fact that it stopped doing a double connection timeout revealed the underlying issue in the app.

**Pull request closed without merging**
