### PR TITLE
adds addFields function

### PR DESCRIPTION
**Pull request by MassiveFermion**
adds addFields function to AggregationCursor.prototype for adding a addFields stage to the aggregation pipeline

### CODE REVIEW

**Comment by MassiveFermion** [comment]
sorry

**Comment by mbroadst** [comment]
@MassiveFermion hey, can you base this against our `next` branch? We are cutting releases from that from here on out

**Comment by MassiveFermion** [comment]
ok

**Comment by mbroadst** [comment]
closing in favor of #2117 which is based against `next`

**Pull request closed without merging**
