### PR TITLE
refactor!: remove deprecated find options

### PR DESCRIPTION
**Pull request by reggi**
* Unsure if this was done correctly.
* Do we want to remove deprecated options from the options object as well?

### CODE REVIEW

**Review by emadum — CHANGES_REQUESTED** [review]
The builder methods also need to be removed, see e.g. [maxScan](https://github.com/mongodb/node-mongodb-native/blob/fe4821cb06a21c1a2a7d7350a5cd4dab7e5ebf0b/src/cursor/cursor.ts#L261-L274). Can you also run an Evergreen patch and link it here, since it's not automated on PRs not based on master?

**Comment by reggi** [comment]
* [ ] Evergreen, will add check when passes: https://spruce.mongodb.com/version/5f8483980ae6061d5c01f597/tasks

**Review by emadum — APPROVED** [review]
LGTM, but I'm wondering why the entire `deprecate_warning.test.js` was deleted? That seems like it's intended to generally ensure our deprecation utilities are working correctly, and we should probably update it to use some other deprecated fields rather than just removing it.

**Comment by reggi** [comment]
> LGTM, but I'm wondering why the entire `deprecate_warning.test.js` was deleted? That seems like it's intended to generally ensure our deprecation utilities are working correctly, and we should probably update it to use some other deprecated fields rather than just removing it.

I went crazy looking for those fields in the tests, I didn't realize it was a stub and doesn't use find, re-enabled.

**Review by nbbeeken — APPROVED** [review]

**Comment by mbroadst** [comment]
@reggi it looks like you still deleted the `deprecate_warning.test.js` file, was that intentional?

**Comment by reggi** [comment]
Total accident. Didn't push the update. https://github.com/mongodb/node-mongodb-native/pull/2585

**Pull request merged**
