### PR TITLE
fix(*): restore ability to webpack by removing `makeLazyLoader`

### PR DESCRIPTION
**Pull request by kvwalker**
* fix(lib): remove makeLazyLoader

* memoize lazy loading function

### CODE REVIEW

**Comment by kvwalker** [comment]
This PR is just applying the commit from `master` to `next`.

**Comment by mbroadst** [comment]
@kvwalker is this blocking you on `next`? I generally do more wholistic merges periodically, if it can wait until then I'd prefer to lump it in with other changes

**Comment by kvwalker** [comment]
It's not blocking me so I'm fine waiting!

**Comment by mbroadst** [comment]
Will be ported to `next` at next merge point

**Pull request closed without merging**
