### PR TITLE
fix: allow event loop to process during wait queue processing

### PR DESCRIPTION
**Pull request by mbroadst**
Running `processWaitQueue` on the next tick allows the event loop to process while the connection pool is processing large numbers of wait queue members.

NODE-2803

### CODE REVIEW

**Review by reggi — APPROVED** [review]

**Review by emadum — APPROVED** [review]
LGTM, but it looks like this made a test start failing in CI (unless that's unrelated)

**Review by nbbeeken — APPROVED** [review]
LGTM

**Comment by vkarpov15** [comment]
Unfortunately this is a breaking change for anyone that uses [Sinon's `useFakeTimers()` for testing](https://sinonjs.org/releases/v1.17.6/fake-timers/), see https://github.com/Automattic/mongoose/issues/9417. Mongoose strongly advises [against using timer mocks](https://mongoosejs.com/docs/jest.html#timer-mocks), but people use them anyway, so I think it's worth thinking about: do we need to use `setImmediate()` here, or can we get away with using `process.nextTick()`, which sinon doesn't stub?

**Comment by mbroadst** [comment]
@vkarpov15 hmm, the original implementation used `process.nextTick` but after discussion around the guidance in [this document](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/) (specifically "We recommend developers use setImmediate() in all cases because it's easier to reason about.") we opted to use `setImmediate`. 

There's a possibility when using `process.nextTick` that we will still be too greedy and won't ever allow the event loop to process critical events. I think your guidance to those users is correct, they should not be mocking timers outside of unit tests. Perhaps your page on using mock timers could be updated to use the workarounds you provided them?

**Pull request merged**
