### PR TITLE
Allow multiple map calls

### PR DESCRIPTION
**Pull request by Robbilie**
before, calling map multiple times on a cursor resulted in only the last map transform to be applied.

### CODE REVIEW

**Comment by christkv** [comment]
Do you mind adding a test case to show the usage pattern you are trying to fix. Also arrow functions cannot be used as we support node all the way back to 0.10.x in the 2.x branch.

**Comment by Robbilie** [comment]
i will try :)

**Comment by Robbilie** [comment]
is that ok?

**Comment by christkv** [comment]
@mbroadst what do you think ?

**Comment by mbroadst** [comment]
LGTM

**Pull request merged**
