### PR TITLE
test(NODE-6120): Implement Unified test runner changes for CSOT

### PR DESCRIPTION
**Pull request by W-A-James**
#### What is changing?

- Implement `$lte` match operator
- Implement `isTimeoutError` option
- Pull in valid/pass tests from [CSOT test format changes PR](https://github.com/mongodb/specifications/pull/959)

##### Is there new documentation needed for these changes?

No

### Double check the following

- [X] Ran `npm run check:lint` script
- [X] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [X] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [X] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

### CODE REVIEW

**Comment by durran** [comment]
evergreen patch

**Comment by durran** [comment]
evergreen patch

**Comment by durran** [comment]
evergreen patch

**Review by durran — APPROVED** [review]

**Review by baileympearson — APPROVED** [review]

**Comment by W-A-James** [comment]
Heads up, rebasing onto the updated feature branch, so hold off on merging. Will update once done

**Comment by W-A-James** [comment]
Rebase complete

**Pull request merged**
