### PR TITLE
add node v12 for travis tests

### PR DESCRIPTION
**Pull request by adityapatadia**
## Description

**What changed?**

**Are there any files to ignore?**

### CODE REVIEW

**Comment by mbroadst** [comment]
@adityapatadia thanks for your contribution!

**Comment by daprahamian** [comment]
@adityapatadia to answer your questions:

## Why does the library have many outdated packages?

There are multiple reasons our dependencies are lagging behind. The two biggest ones are:

* We cannot upgrade until we drop support for older versions of Node. We currently support back to Node v4, and upgrading our dependencies cannot happen until we drop support for certain node versions. `mocha` is a good example of this
* The upgrade is risky / dangerous. In `bson`'s case, the library is used in numerous places throughout the driver, and is also partially exposed as a user API. Upgrading BSON would require a lot of work to ensure that we do not introduce bugs or breaking behavior.

In both of these cases, we are holding off on these upgrades until we release a new major version of the driver.

### What are `peerOptionalDependencies`?

npm has a concept of `peerDependencies` (dependencies that are needed to use the package, and are not automatically installed), and `optionalDependencies` (dependencies that the package will attempt to install, but are not necessary for actually running the package). `peerOptionalDependencies` are a combination of these two concepts. They are "optional" in that they are not absolutely necessary for running the driver, and "peer" in that they will not automatically be installed. These fields are leveraged by [`require_optional`](https://www.npmjs.com/package/require_optional), which will ensure that if the packages are pulled in, and will provide proper error messages if the wrong version is installed.

As for what they indicate for you, they simply indicate what version of those packages you need to install if you want their functionality. `kerberos` is optional, so you do not need to install it, but if you do want to use it, you need to make sure that you install version that matches `^1.1.0`.

Hope these answers help,
Dan

**Comment by adityapatadia** [comment]
Thanks a lot for nice explanation. I installed bson-ext and it works better now. 

Regards,
Aditya Patadia

**Comment by adityapatadia** [comment]
@daprahamian this new issue has popped up with the new topology: https://jira.mongodb.org/browse/NODE-2092

It's preventing use of bson-ext.

**Pull request merged**
