### PR TITLE
NODE-426 handle writes to GridStoreStream instances properly

### PR DESCRIPTION
**Pull request by itsjustcon**
fixes stream.pipe compatibility for writable GridStoreStream objects

### CODE REVIEW

**Comment by christkv** [comment]
can you provide a breaking test case ?

**Comment by christkv** [comment]
I'm trying to write a breaking test case without much success so far.

**Comment by christkv** [comment]
ping

**Comment by itsjustcon** [comment]
The last tutorial on this page: http://mongodb.github.io/node-mongodb-native/2.0/tutorials/streams/ "Streaming a File into GridFS" will break by itself due to this. Try running that example

**Pull request merged**
