### PR TITLE
add node v12 for travis tests

### PR DESCRIPTION
**Pull request by adityapatadia**
## Description

**What changed?**

**Are there any files to ignore?**

### CODE REVIEW

**Comment by adityapatadia** [comment]
I have created new PR against next branch: https://github.com/mongodb/node-mongodb-native/pull/2127

**Comment by adityapatadia** [comment]
@daprahamian I am sorry but I am not able to correct the errors. I can see some issue with file `kerberos_common.h` but I have very limited knowledge of C.

**Comment by daprahamian** [comment]
@adityapatadia can you update the version of Kerberos in your branch to 1.1.3? That version should have support for Node 12.

**Comment by adityapatadia** [comment]
I have updated and it worked with node 12, but some GridFS tests are failing.

Btw, I see lot of dependencies are outdated. May be you can consider using something like dependabot: https://dependabot.com

**Comment by adityapatadia** [comment]
Please check the log here: https://travis-ci.org/mongodb/node-mongodb-native/jobs/581751661

**Comment by mbroadst** [comment]
closing in favor of patch applied this morning to `next`

**Pull request closed without merging**
